# Generated by Django 5.2.1 on 2025-07-11 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioDeCitas',
            fields=[
                ('id_calendario', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FichaClinica',
            fields=[
                ('id_ficha', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rut_paciente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('contacto', models.IntegerField(blank=True, null=True)),
                ('tipo_sangre', models.CharField(blank=True, max_length=3, null=True)),
                ('genero', models.CharField(blank=True, max_length=10, null=True)),
                ('sistema_salud', models.CharField(blank=True, max_length=20, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=20, null=True)),
                ('calle', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_casa', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDePago',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('boleta', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='EnfermedadBucal',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('id_ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.fichaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('dosis', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('id_ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.fichaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='Odontologo',
            fields=[
                ('rut_odontologo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_de_casa', models.CharField(blank=True, max_length=10, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('id_calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.calendariodecitas')),
            ],
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='rut_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.paciente'),
        ),
        migrations.CreateModel(
            name='Radiografia',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('imagen', models.BinaryField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('id_ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.fichaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('asunto', models.CharField(blank=True, max_length=300, null=True)),
                ('bloque_horario', models.CharField(blank=True, max_length=30, null=True)),
                ('id_ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.fichaclinica')),
                ('rut_odontologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.odontologo')),
                ('id_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.registrodepago')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id_tratamiento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('presupuesto', models.IntegerField(blank=True, null=True)),
                ('id_ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.fichaclinica')),
                ('id_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.registrodepago')),
                ('rut_odontologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.odontologo')),
            ],
        ),
        migrations.CreateModel(
            name='AccedeEdita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.fichaclinica')),
                ('rut_odontologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.odontologo')),
            ],
            options={
                'unique_together': {('id_ficha', 'rut_odontologo')},
            },
        ),
        migrations.CreateModel(
            name='Usa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.material')),
                ('rut_odontologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.odontologo')),
            ],
            options={
                'unique_together': {('rut_odontologo', 'id_material')},
            },
        ),
    ]
